post: example: mcuboot: freeze mcuboot to specific version
memfault/interrupt pull request #204
Opened 2021-06-11 22:56 UTC by sophiekovalevsky

This commit sets mcu boot repository used in example to a state where
the porting code implemented here is able to compile. The reason why
doing this is that, mcu boot so far has introduced several changes
that are missing in example. This will allow to compile the code right
away.

2021-06-12 00:48 UTC, franc0is requested changes
Thank you for the PR, @sophiekovalevsky! One small thing: you forgot to refresh the submodules after checkout. Happy to merge once this is fixed!

2021-06-12 02:08 UTC, sophiekovalevsky commented
@franc0is thanks for that tiny detail. Should be ready now.

2021-06-14 16:29 UTC, franc0is approved these changes

2021-06-14 16:29 UTC, franc0is commented
Thank you! You are ok to merge.

2021-09-01 04:07 UTC, merged