Update images and change text accordingly
memfault/interrupt pull request #415
Opened 2023-12-25 21:48 UTC by Zamuhrishka

I am writing to inform you of a recent update I made to the article. I have replaced the original images with new ones that are not only aesthetically pleasing but also align with a consistent style that will be maintained throughout the series. I believe these enhancements will significantly elevate the professional appearance of the article.

2023-12-29 15:33 UTC, gminn requested changes
I'm a fan of the new sketch-style images and tweaks to highlight the high and low values, among other improvements. Thanks for submitting these changes! I have some nitpick comments about format and readability for you before we merge. Let me know if you have any questions!

2023-12-29 15:33 UTC, gminn commented on img/jtag-part1/shift-dr-state.gif
Same comment here about space before the TDO label

2024-01-01 23:17 UTC, Zamuhrishka commented on img/jtag-part1/debug-tap-2.gif
Fixed. Thank you.

2024-01-01 23:18 UTC, Zamuhrishka commented on img/jtag-part1/update-dr-state-ir.gif
Fixed. Thank you.

2024-01-01 23:18 UTC, Zamuhrishka commented on img/jtag-part1/shift-reg.gif
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/shift-reg.gif
I changed the width but I`m unsure this is the correct value. Please take a look.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/shift-dr-state.gif
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/debug-tap.gif
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/jtag-state-machine.png
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/shift-reg.gif
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/capture-dr-state-dr.gif
Fixed. Thank you.

2024-01-01 23:20 UTC, Zamuhrishka commented on img/jtag-part1/idcode-instruction-reg.png
Fixed. Thank you.

2024-01-01 23:21 UTC, Zamuhrishka commented on img/jtag-part1/jtag-control-signals.png
Fixed. Thank you.

2024-01-01 23:25 UTC, Zamuhrishka commented on img/jtag-part1/jtag-example.gif
I would like to ask you to let me not make any changes to jtag-example.gif because it would be time consuming. I need to modify 23 frames of this gif, and I need to be careful not to make mistakes in each of these frames.

2024-01-01 23:26 UTC, Zamuhrishka commented on img/jtag-part1/jtag-example.gif
The same comment about jtag-example.gif changes

2024-01-02 13:54 UTC, gminn commented on img/jtag-part1/shift-reg.gif
Looks great!

2024-01-02 14:01 UTC, gminn commented on img/jtag-part1/jtag-example.gif
Understood, thanks for considering anyways. Readers can zoom in if needed.

2024-01-02 14:02 UTC, gminn approved these changes
Thank you for addressing my comments!

2024-01-02 14:04 UTC, merged

2024-01-02 16:51 UTC, Zamuhrishka commented
Thank you @gminn for your comments. They made the images better. :)

2024-01-02 16:52 UTC, Zamuhrishka commented on img/jtag-part1/jtag-example.gif
Thank you. You safe my day :)